# Generated by Django 4.2 on 2026-01-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('city', models.CharField(choices=[('mumbai', 'Mumbai'), ('london', 'London')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('is_assemblage', models.BooleanField(default=False, editable=False)),
                ('is_fragment', models.BooleanField(default=False)),
                ('image', sorl.thumbnail.fields.ImageField(help_text='Upload image of object', upload_to='uploads/items/')),
                ('width', models.DecimalField(blank=True, decimal_places=3, help_text='Width of object, in cm', max_digits=8, null=True)),
                ('title', models.CharField(help_text='A title for this object', max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, help_text='Some description for the object (optional)')),
                ('utility', models.TextField(blank=True, help_text='Definition / Relevance')),
                ('utility_url', models.URLField(blank=True, help_text='URL with definition (wiki link, etc)', max_length=1024)),
                ('significance', models.TextField(blank=True, help_text='Personal history / Travelogue:journey of an object')),
                ('image_courtesy', models.CharField(blank=True, help_text='name of contributor', max_length=512)),
                ('new_imaginations', models.TextField(blank=True, editable=False)),
                ('published', models.BooleanField(default=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazaar.market')),
                ('parent_items', models.ManyToManyField(editable=False, related_name='child_items', to='bazaar.item')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_assemblage', '-id'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
                ('items', models.ManyToManyField(to='bazaar.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
